apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: {{ $.Values.worker.image.repository }}/{{ $.Values.worker.image.project }}/{{ $.Values.worker.image.name }}:{{ $.Values.worker.image.tag }}
      #- image: dockersamples/examplevotingapp_worker
        name: worker
        resources:
          requests:
            memory: "128Mi"
            cpu: "300m"
